version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./screen:/app/screen
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    container_name: sistema_mecanica
